export const months = [
  "Enero",
  "Febrero",
  "Marzo",
  "Abril",
  "Mayo",
  "Junio",
  "Julio",
  "Agosto",
  "Septiembre",
  "Octubre",
  "Noviembre",
  "Diciembre",
];

export const states = [
  "AGUASCALIENTES",
  "BAJA CALIFORNIA",
  "BAJA CALIFORNIA SUR",
  "CAMPECHE",
  "COAHUILA",
  "COLIMA",
  "CHIAPAS",
  "CHIHUAHUA",
  "CDMX",
  "DURANGO",
  "GUANAJUATO",
  "GUERRERO",
  "HIDALGO",
  "JALISCO",
  "MEXICO",
  "MICHOACAN",
  "MORELOS",
  "NAYARIT",
  "NUEVO LEON",
  "OAXACA",
  "PUEBLA",
  "QUERETARO",
  "QUINTANA ROO",
  "SAN LUIS POTOSI",
  "SINALOA",
  "SONORA",
  "TABASCO",
  "TAMAULIPAS",
  "TLAXCALA",
  "VERACRUZ",
  "YUCATAN",
  "ZACATECAS",
];

/* Abandon all hope, ye who enter here. */
export const mun = [
  /*01*/ [""],
  /*02*/ [""],
  /*03*/ [""],
  /*04*/ [""],
  /*05*/ [""],
  /*06*/ [""],
  /*07*/ [""],
  /*08*/ [""],
  /*09*/ [""],
  /*10*/ [""],
  /*11*/ [""],
  /*12*/ [""],
  /*13*/ [""],
  /*14*/ [""],
  /*15*/ [""],
  /*16*/ [""],
  /*17*/ [""],
  /*18*/ [""],
  /*19*/ [
    "Abasolo",
    "Agualeguas",
    "Los Aldamas",
    "Allende",
    "Anáhuac",
    "Apodaca",
    "Aramberri",
    "Bustamante",
    "Cadereyta Jiménez",
    "El Carmen",
    "Cerralvo",
    "Ciénega de Flores",
    "China",
    "Doctor Arroyo",
    "Doctor Coss",
    "Doctor González",
    "Galeana",
    "García",
    "San Pedro Garza García",
    "General Bravo",
    "General Escobedo",
    "General Terán",
    "General Treviño",
    "General Zaragoza",
    "General Zuazua",
    "Guadalupe",
    "Los Herreras",
    "Higueras",
    "Hualahuises",
    "Iturbide",
    "Juárez",
    "Lampazos de Naranjo",
    "Linares",
    "Marín",
    "Melchor Ocampo",
    "Mier y Noriega",
    "Mina",
    "Montemorelos",
    "Monterrey",
    "Parás",
    "Pesquería",
    "Los Ramones",
    "Rayones",
    "Sabinas Hidalgo",
    "Salinas Victoria",
    "San Nicolás de los Garza",
    "Hidalgo",
    "Santa Catarina",
    "Santiago",
    "Vallecillo",
    "Villaldama",
  ],
  /*20*/ [""],
  /*21*/ [""],
  /*22*/ [""],
  /*23*/ [""],
  /*24*/ [""],
  /*25*/ [""],
  /*26*/ [""],
  /*27*/ [""],
  /*28*/ [
    "Abasolo",
    "Aldama",
    "Altamira",
    "Antiguo Morelos",
    "Burgos",
    "Bustamante",
    "Camargo",
    "Casas",
    "Ciudad Madero",
    "Cruillas",
    "Gómez Farías",
    "González",
    "Güémez",
    "Guerrero",
    "Gustavo Díaz Ordaz",
    "Hidalgo",
    "Jaumave",
    "Jiménez",
    "Llera",
    "Mainero",
    "El Mante",
    "Matamoros",
    "Méndez",
    "Mier",
    "Miguel Alemán",
    "Miquihuana",
    "Nuevo Laredo",
    "Nuevo Morelos",
    "Ocampo",
    "Padilla",
    "Palmillas",
    "Reynosa",
    "Río Bravo",
    "San Carlos",
    "San Fernando",
    "San Nicolás",
    "Soto la Marina",
    "Tampico",
    "Tula",
    "Valle Hermoso",
    "Victoria",
    "Villagrán",
    "Xicoténcatl",
  ],
  /*29*/ [""],
  /*30*/ [
    "Acajete",
    "Acatlán",
    "Acayucan",
    "Actopan",
    "Acula",
    "Acultzingo",
    "Camarón de Tejeda",
    "Alpatláhuac",
    "Alto Lucero de Gutiérrez Barrios",
    "Altotonga",
    "Alvarado",
    "Amatitlán",
    "Naranjos Amatlán",
    "Amatlán de los Reyes",
    "Angel R. Cabada",
    "La Antigua",
    "Apazapan",
    "Aquila",
    "Astacinga",
    "Atlahuilco",
    "Atoyac",
    "Atzacan",
    "Atzalan",
    "Tlaltetela",
    "Ayahualulco",
    "Banderilla",
    "Benito Juárez",
    "Boca del Río",
    "Calcahualco",
    "Camerino Z. Mendoza",
    "Carrillo Puerto",
    "Catemaco",
    "Cazones de Herrera",
    "Cerro Azul",
    "Citlaltépetl",
    "Coacoatzintla",
    "Coahuitlán",
    "Coatepec",
    "Coatzacoalcos",
    "Coatzintla",
    "Coetzala",
    "Colipa",
    "Comapa",
    "Córdoba",
    "Cosamaloapan de Carpio",
    "Cosautlán de Carvajal",
    "Coscomatepec",
    "Cosoleacaque",
    "Cotaxtla",
    "Coxquihui",
    "Coyutla",
    "Cuichapa",
    "Cuitláhuac",
    "Chacaltianguis",
    "Chalma",
    "Chiconamel",
    "Chiconquiaco",
    "Chicontepec",
    "Chinameca",
    "Chinampa de Gorostiza",
    "Las Choapas",
    "Chocamán",
    "Chontla",
    "Chumatlán",
    "Emiliano Zapata",
    "Espinal",
    "Filomeno Mata",
    "Fortín",
    "Gutiérrez Zamora",
    "Hidalgotitlán",
    "Huatusco",
    "Huayacocotla",
    "Hueyapan de Ocampo",
    "Huiloapan de Cuauhtémoc",
    "Ignacio de la Llave",
    "Ilamatlán",
    "Isla",
    "Ixcatepec",
    "Ixhuacán de los Reyes",
    "Ixhuatlán del Café",
    "Ixhuatlancillo",
    "Ixhuatlán del Sureste",
    "Ixhuatlán de Madero",
    "Ixmatlahuacan",
    "Ixtaczoquitlán",
    "Jalacingo",
    "Xalapa",
    "Jalcomulco",
    "Jáltipan",
    "Jamapa",
    "Jesús Carranza",
    "Xico",
    "Jilotepec",
    "Juan Rodríguez Clara",
    "Juchique de Ferrer",
    "Landero y Coss",
    "Lerdo de Tejada",
    "Magdalena",
    "Maltrata",
    "Manlio Fabio Altamirano",
    "Mariano Escobedo",
    "Martínez de la Torre",
    "Mecatlán",
    "Mecayapan",
    "Medellín de Bravo",
    "Miahuatlán",
    "Las Minas",
    "Minatitlán",
    "Misantla",
    "Mixtla de Altamirano",
    "Moloacán",
    "Naolinco",
    "Naranjal",
    "Nautla",
    "Nogales",
    "Oluta",
    "Omealca",
    "Orizaba",
    "Otatitlán",
    "Oteapan",
    "Ozuluama de Mascareñas",
    "Pajapan",
    "Pánuco",
    "Papantla",
    "Paso del Macho",
    "Paso de Ovejas",
    "La Perla",
    "Perote",
    "Platón Sánchez",
    "Playa Vicente",
    "Poza Rica de Hidalgo",
    "Las Vigas de Ramírez",
    "Pueblo Viejo",
    "Puente Nacional",
    "Rafael Delgado",
    "Rafael Lucio",
    "Los Reyes",
    "Río Blanco",
    "Saltabarranca",
    "San Andrés Tenejapan",
    "San Andrés Tuxtla",
    "San Juan Evangelista",
    "Santiago Tuxtla",
    "Sayula de Alemán",
    "Soconusco",
    "Sochiapa",
    "Soledad Atzompa",
    "Soledad de Doblado",
    "Soteapan",
    "Tamalín",
    "Tamiahua",
    "Tampico Alto",
    "Tancoco",
    "Tantima",
    "Tantoyuca",
    "Tatatila",
    "Castillo de Teayo",
    "Tecolutla",
    "Tehuipango",
    "Álamo Temapache",
    "Tempoal",
    "Tenampa",
    "Tenochtitlán",
    "Teocelo",
    "Tepatlaxco",
    "Tepetlán",
    "Tepetzintla",
    "Tequila",
    "José Azueta",
    "Texcatepec",
    "Texhuacán",
    "Texistepec",
    "Tezonapa",
    "Tierra Blanca",
    "Tihuatlán",
    "Tlacojalpan",
    "Tlacolulan",
    "Tlacotalpan",
    "Tlacotepec de Mejía",
    "Tlachichilco",
    "Tlalixcoyan",
    "Tlalnelhuayocan",
    "Tlapacoyan",
    "Tlaquilpa",
    "Tlilapan",
    "Tomatlán",
    "Tonayán",
    "Totutla",
    "Tuxpan",
    "Tuxtilla",
    "Ursulo Galván",
    "Vega de Alatorre",
    "Veracruz",
    "Villa Aldama",
    "Xoxocotla",
    "Yanga",
    "Yecuatla",
    "Zacualpan",
    "Zaragoza",
    "Zentla",
    "Zongolica",
    "Zontecomatlán de López y Fuentes",
    "Zozocolco de Hidalgo",
    "Agua Dulce",
    "El Higo",
    "Nanchital de Lázaro Cárdenas del Río",
    "Tres Valles",
    "Carlos A. Carrillo",
    "Tatahuicapan de Juárez",
    "Uxpanapa",
    "San Rafael",
  ],
  /*31*/ [""],
  /*32*/ [""],
];
