export const months = [
  "Enero",
  "Febrero",
  "Marzo",
  "Abril",
  "Mayo",
  "Junio",
  "Julio",
  "Agosto",
  "Septiembre",
  "Octubre",
  "Noviembre",
  "Diciembre",
];

export const states = [
  "AGUASCALIENTES",
  "BAJA CALIFORNIA",
  "BAJA CALIFORNIA SUR",
  "CAMPECHE",
  "COAHUILA",
  "COLIMA",
  "CHIAPAS",
  "CHIHUAHUA",
  "CDMX",
  "DURANGO",
  "GUANAJUATO",
  "GUERRERO",
  "HIDALGO",
  "JALISCO",
  "MEXICO",
  "MICHOACAN",
  "MORELOS",
  "NAYARIT",
  "NUEVO LEON",
  "OAXACA",
  "PUEBLA",
  "QUERETARO",
  "QUINTANA ROO",
  "SAN LUIS POTOSI",
  "SINALOA",
  "SONORA",
  "TABASCO",
  "TAMAULIPAS",
  "TLAXCALA",
  "VERACRUZ",
  "YUCATAN",
  "ZACATECAS",
];

/* Abandon all hope, ye who enter here. */
export const mun = [
  /*01*/ [
    "Aguascalientes",
    "Asientos",
    "Calvillo",
    "Cosío",
    "Jesús María",
    "Pabellón de Arteaga",
    "Rincón de Romos",
    "San José de Gracia",
    "Tepezalá",
    "El Llano",
    "San Francisco de los Romo",
  ],
  /*02*/ [
    "Ensenada",
    "Mexicali",
    "Tecate",
    "Tijuana",
    "Playas de Rosarito",
    "San Quintín",
    "San Felipe",
  ],
  /*03*/ ["Comondú", "Mulegé", "La Paz", "Los Cabos", "Loreto"],
  /*04*/ [
    "Calkiní",
    "Campeche",
    "Carmen",
    "Champotón",
    "Hecelchakán",
    "Hopelchén",
    "Palizada",
    "Tenabo",
    "Escárcega",
    "Calakmul",
    "Candelaria",
    "Seybaplaya",
    "Dzitbalché",
  ],
  /*05*/ [
    "Abasolo",
    "Acuña",
    "Allende",
    "Arteaga",
    "Candela",
    "Castaños",
    "Cuatro Ciénegas",
    "Escobedo",
    "Francisco I. Madero",
    "Frontera",
    "General Cepeda",
    "Guerrero",
    "Hidalgo",
    "Jiménez",
    "Juárez",
    "Lamadrid",
    "Matamoros",
    "Monclova",
    "Morelos",
    "Múzquiz",
    "Nadadores",
    "Nava",
    "Ocampo",
    "Parras",
    "Piedras Negras",
    "Progreso",
    "Ramos Arizpe",
    "Sabinas",
    "Sacramento",
    "Saltillo",
    "San Buenaventura",
    "San Juan de Sabinas",
    "San Pedro",
    "Sierra Mojada",
    "Torreón",
    "Viesca",
    "Villa Unión",
    "Zaragoza",
  ],
  /*06*/ [""],
  /*07*/ [""],
  /*08*/ [""],
  /*09*/ [""],
  /*10*/ [""],
  /*11*/ [""],
  /*12*/ [""],
  /*13*/ [""],
  /*14*/ [""],
  /*15*/ [""],
  /*16*/ [""],
  /*17*/ [""],
  /*18*/ [""],
  /*19*/ [
    "Abasolo",
    "Agualeguas",
    "Los Aldamas",
    "Allende",
    "Anáhuac",
    "Apodaca",
    "Aramberri",
    "Bustamante",
    "Cadereyta Jiménez",
    "El Carmen",
    "Cerralvo",
    "Ciénega de Flores",
    "China",
    "Doctor Arroyo",
    "Doctor Coss",
    "Doctor González",
    "Galeana",
    "García",
    "San Pedro Garza García",
    "General Bravo",
    "General Escobedo",
    "General Terán",
    "General Treviño",
    "General Zaragoza",
    "General Zuazua",
    "Guadalupe",
    "Los Herreras",
    "Higueras",
    "Hualahuises",
    "Iturbide",
    "Juárez",
    "Lampazos de Naranjo",
    "Linares",
    "Marín",
    "Melchor Ocampo",
    "Mier y Noriega",
    "Mina",
    "Montemorelos",
    "Monterrey",
    "Parás",
    "Pesquería",
    "Los Ramones",
    "Rayones",
    "Sabinas Hidalgo",
    "Salinas Victoria",
    "San Nicolás de los Garza",
    "Hidalgo",
    "Santa Catarina",
    "Santiago",
    "Vallecillo",
    "Villaldama",
  ],
  /*20*/ [
    "Abejones",
    "Acatlán de Pérez Figueroa",
    "Asunción Cacalotepec",
    "Asunción Cuyotepeji",
    "Asunción Ixtaltepec",
    "Asunción Nochixtlán",
    "Asunción Ocotlán",
    "Asunción Tlacolulita",
    "Ayotzintepec",
    "El Barrio de la Soledad",
    "Calihualá",
    "Candelaria Loxicha",
    "Ciénega de Zimatlán",
    "Ciudad Ixtepec",
    "Coatecas Altas",
    "Coicoyán de las Flores",
    "La Compañía",
    "Concepción Buenavista",
    "Concepción Pápalo",
    "Constancia del Rosario",
    "Cosolapa",
    "Cosoltepec",
    "Cuilápam de Guerrero",
    "Cuyamecalco Villa de Zaragoza",
    "Chahuites",
    "Chalcatongo de Hidalgo",
    "Chiquihuitlán de Benito Juárez",
    "Heroica Ciudad de Ejutla de Crespo",
    "Eloxochitlán de Flores Magón",
    "El Espinal",
    "Tamazulápam del Espíritu Santo",
    "Fresnillo de Trujano",
    "Guadalupe Etla",
    "Guadalupe de Ramírez",
    "Guelatao de Juárez",
    "Guevea de Humboldt",
    "Mesones Hidalgo",
    "Villa Hidalgo",
    "Heroica Ciudad de Huajuapan de León",
    "Huautepec",
    "Huautla de Jiménez",
    "Ixtlán de Juárez",
    "Juchitán de Zaragoza",
    "Loma Bonita",
    "Magdalena Apasco",
    "Magdalena Jaltepec",
    "Santa Magdalena Jicotlán",
    "Magdalena Mixtepec",
    "Magdalena Ocotlán",
    "Magdalena Peñasco",
    "Magdalena Teitipac",
    "Magdalena Tequisistlán",
    "Magdalena Tlacotepec",
    "Magdalena Zahuatlán",
    "Mariscala de Juárez",
    "Mártires de Tacubaya",
    "Matías Romero Avendaño",
    "Mazatlán Villa de Flores",
    "Miahuatlán de Porfirio Díaz",
    "Mixistlán de la Reforma",
    "Monjas",
    "Natividad",
    "Nazareno Etla",
    "Nejapa de Madero",
    "Ixpantepec Nieves",
    "Santiago Niltepec",
    "Oaxaca de Juárez",
    "Ocotlán de Morelos",
    "La Pe",
    "Pinotepa de Don Luis",
    "Pluma Hidalgo",
    "San José del Progreso",
    "Putla Villa de Guerrero",
    "Santa Catarina Quioquitani",
    "Reforma de Pineda",
    "La Reforma",
    "Reyes Etla",
    "Rojas de Cuauhtémoc",
    "Salina Cruz",
    "San Agustín Amatengo",
    "San Agustín Atenango",
    "San Agustín Chayuco",
    "San Agustín de las Juntas",
    "San Agustín Etla",
    "San Agustín Loxicha",
    "San Agustín Tlacotepec",
    "San Agustín Yatareni",
    "San Andrés Cabecera Nueva",
    "San Andrés Dinicuiti",
    "San Andrés Huaxpaltepec",
    "San Andrés Huayápam",
    "San Andrés Ixtlahuaca",
    "San Andrés Lagunas",
    "San Andrés Nuxiño",
    "San Andrés Paxtlán",
    "San Andrés Sinaxtla",
    "San Andrés Solaga",
    "San Andrés Teotilálpam",
    "San Andrés Tepetlapa",
    "San Andrés Yaá",
    "San Andrés Zabache",
    "San Andrés Zautla",
    "San Antonino Castillo Velasco",
    "San Antonino el Alto",
    "San Antonino Monte Verde",
    "San Antonio Acutla",
    "San Antonio de la Cal",
    "San Antonio Huitepec",
    "San Antonio Nanahuatípam",
    "San Antonio Sinicahua",
    "San Antonio Tepetlapa",
    "San Baltazar Chichicápam",
    "San Baltazar Loxicha",
    "San Baltazar Yatzachi el Bajo",
    "San Bartolo Coyotepec",
    "San Bartolomé Ayautla",
    "San Bartolomé Loxicha",
    "San Bartolomé Quialana",
    "San Bartolomé Yucuañe",
    "San Bartolomé Zoogocho",
    "San Bartolo Soyaltepec",
    "San Bartolo Yautepec",
    "San Bernardo Mixtepec",
    "Heroica Villa de San Blas Atempa",
    "San Carlos Yautepec",
    "San Cristóbal Amatlán",
    "San Cristóbal Amoltepec",
    "San Cristóbal Lachirioag",
    "San Cristóbal Suchixtlahuaca",
    "San Dionisio del Mar",
    "San Dionisio Ocotepec",
    "San Dionisio Ocotlán",
    "San Esteban Atatlahuca",
    "San Felipe Jalapa de Díaz",
    "San Felipe Tejalápam",
    "San Felipe Usila",
    "San Francisco Cahuacuá",
    "San Francisco Cajonos",
    "San Francisco Chapulapa",
    "San Francisco Chindúa",
    "San Francisco del Mar",
    "San Francisco Huehuetlán",
    "San Francisco Ixhuatán",
    "San Francisco Jaltepetongo",
    "San Francisco Lachigoló",
    "San Francisco Logueche",
    "San Francisco Nuxaño",
    "San Francisco Ozolotepec",
    "San Francisco Sola",
    "San Francisco Telixtlahuaca",
    "San Francisco Teopan",
    "San Francisco Tlapancingo",
    "San Gabriel Mixtepec",
    "San Ildefonso Amatlán",
    "San Ildefonso Sola",
    "San Ildefonso Villa Alta",
    "San Jacinto Amilpas",
    "San Jacinto Tlacotepec",
    "San Jerónimo Coatlán",
    "San Jerónimo Silacayoapilla",
    "San Jerónimo Sosola",
    "San Jerónimo Taviche",
    "San Jerónimo Tecóatl",
    "San Jorge Nuchita",
    "San José Ayuquila",
    "San José Chiltepec",
    "San José del Peñasco",
    "San José Estancia Grande",
    "San José Independencia",
    "San José Lachiguiri",
    "San José Tenango",
    "San Juan Achiutla",
    "San Juan Atepec",
    "Ánimas Trujano",
    "San Juan Bautista Atatlahuca",
    "San Juan Bautista Coixtlahuaca",
    "San Juan Bautista Cuicatlán",
    "San Juan Bautista Guelache",
    "San Juan Bautista Jayacatlán",
    "San Juan Bautista Lo de Soto",
    "San Juan Bautista Suchitepec",
    "San Juan Bautista Tlacoatzintepec",
    "San Juan Bautista Tlachichilco",
    "San Juan Bautista Tuxtepec",
    "San Juan Cacahuatepec",
    "San Juan Cieneguilla",
    "San Juan Coatzóspam",
    "San Juan Colorado",
    "San Juan Comaltepec",
    "San Juan Cotzocón",
    "San Juan Chicomezúchil",
    "San Juan Chilateca",
    "San Juan del Estado",
    "San Juan del Río",
    "San Juan Diuxi",
    "San Juan Evangelista Analco",
    "San Juan Guelavía",
    "San Juan Guichicovi",
    "San Juan Ihualtepec",
    "San Juan Juquila Mixes",
    "San Juan Juquila Vijanos",
    "San Juan Lachao",
    "San Juan Lachigalla",
    "San Juan Lajarcia",
    "San Juan Lalana",
    "San Juan de los Cués",
    "San Juan Mazatlán",
    "San Juan Mixtepec",
    "San Juan Mixtepec",
    "San Juan Ñumí",
    "San Juan Ozolotepec",
    "San Juan Petlapa",
    "San Juan Quiahije",
    "San Juan Quiotepec",
    "San Juan Sayultepec",
    "San Juan Tabaá",
    "San Juan Tamazola",
    "San Juan Teita",
    "San Juan Teitipac",
    "San Juan Tepeuxila",
    "San Juan Teposcolula",
    "San Juan Yaeé",
    "San Juan Yatzona",
    "San Juan Yucuita",
    "San Lorenzo",
    "San Lorenzo Albarradas",
    "San Lorenzo Cacaotepec",
    "San Lorenzo Cuaunecuiltitla",
    "San Lorenzo Texmelúcan",
    "San Lorenzo Victoria",
    "San Lucas Camotlán",
    "San Lucas Ojitlán",
    "San Lucas Quiaviní",
    "San Lucas Zoquiápam",
    "San Luis Amatlán",
    "San Marcial Ozolotepec",
    "San Marcos Arteaga",
    "San Martín de los Cansecos",
    "San Martín Huamelúlpam",
    "San Martín Itunyoso",
    "San Martín Lachilá",
    "San Martín Peras",
    "San Martín Tilcajete",
    "San Martín Toxpalan",
    "San Martín Zacatepec",
    "San Mateo Cajonos",
    "Capulálpam de Méndez",
    "San Mateo del Mar",
    "San Mateo Yoloxochitlán",
    "San Mateo Etlatongo",
    "San Mateo Nejápam",
    "San Mateo Peñasco",
    "San Mateo Piñas",
    "San Mateo Río Hondo",
    "San Mateo Sindihui",
    "San Mateo Tlapiltepec",
    "San Melchor Betaza",
    "San Miguel Achiutla",
    "San Miguel Ahuehuetitlán",
    "San Miguel Aloápam",
    "San Miguel Amatitlán",
    "San Miguel Amatlán",
    "San Miguel Coatlán",
    "San Miguel Chicahua",
    "San Miguel Chimalapa",
    "San Miguel del Puerto",
    "San Miguel del Río",
    "San Miguel Ejutla",
    "San Miguel el Grande",
    "San Miguel Huautla",
    "San Miguel Mixtepec",
    "San Miguel Panixtlahuaca",
    "San Miguel Peras",
    "San Miguel Piedras",
    "San Miguel Quetzaltepec",
    "San Miguel Santa Flor",
    "Villa Sola de Vega",
    "San Miguel Soyaltepec",
    "San Miguel Suchixtepec",
    "Villa Talea de Castro",
    "San Miguel Tecomatlán",
    "San Miguel Tenango",
    "San Miguel Tequixtepec",
    "San Miguel Tilquiápam",
    "San Miguel Tlacamama",
    "San Miguel Tlacotepec",
    "San Miguel Tulancingo",
    "San Miguel Yotao",
    "San Nicolás",
    "San Nicolás Hidalgo",
    "San Pablo Coatlán",
    "San Pablo Cuatro Venados",
    "San Pablo Etla",
    "San Pablo Huitzo",
    "San Pablo Huixtepec",
    "San Pablo Macuiltianguis",
    "San Pablo Tijaltepec",
    "San Pablo Villa de Mitla",
    "San Pablo Yaganiza",
    "San Pedro Amuzgos",
    "San Pedro Apóstol",
    "San Pedro Atoyac",
    "San Pedro Cajonos",
    "San Pedro Coxcaltepec Cántaros",
    "San Pedro Comitancillo",
    "San Pedro el Alto",
    "San Pedro Huamelula",
    "San Pedro Huilotepec",
    "San Pedro Ixcatlán",
    "San Pedro Ixtlahuaca",
    "San Pedro Jaltepetongo",
    "San Pedro Jicayán",
    "San Pedro Jocotipac",
    "San Pedro Juchatengo",
    "San Pedro Mártir",
    "San Pedro Mártir Quiechapa",
    "San Pedro Mártir Yucuxaco",
    "San Pedro Mixtepec",
    "San Pedro Mixtepec",
    "San Pedro Molinos",
    "San Pedro Nopala",
    "San Pedro Ocopetatillo",
    "San Pedro Ocotepec",
    "San Pedro Pochutla",
    "San Pedro Quiatoni",
    "San Pedro Sochiápam",
    "San Pedro Tapanatepec",
    "San Pedro Taviche",
    "San Pedro Teozacoalco",
    "San Pedro Teutila",
    "San Pedro Tidaá",
    "San Pedro Topiltepec",
    "San Pedro Totolápam",
    "Villa de Tututepec",
    "San Pedro Yaneri",
    "San Pedro Yólox",
    "San Pedro y San Pablo Ayutla",
    "Villa de Etla",
    "San Pedro y San Pablo Teposcolula",
    "San Pedro y San Pablo Tequixtepec",
    "San Pedro Yucunama",
    "San Raymundo Jalpan",
    "San Sebastián Abasolo",
    "San Sebastián Coatlán",
    "San Sebastián Ixcapa",
    "San Sebastián Nicananduta",
    "San Sebastián Río Hondo",
    "San Sebastián Tecomaxtlahuaca",
    "San Sebastián Teitipac",
    "San Sebastián Tutla",
    "San Simón Almolongas",
    "San Simón Zahuatlán",
    "Santa Ana",
    "Santa Ana Ateixtlahuaca",
    "Santa Ana Cuauhtémoc",
    "Santa Ana del Valle",
    "Santa Ana Tavela",
    "Santa Ana Tlapacoyan",
    "Santa Ana Yareni",
    "Santa Ana Zegache",
    "Santa Catalina Quierí",
    "Santa Catarina Cuixtla",
    "Santa Catarina Ixtepeji",
    "Santa Catarina Juquila",
    "Santa Catarina Lachatao",
    "Santa Catarina Loxicha",
    "Santa Catarina Mechoacán",
    "Santa Catarina Minas",
    "Santa Catarina Quiané",
    "Santa Catarina Tayata",
    "Santa Catarina Ticuá",
    "Santa Catarina Yosonotú",
    "Santa Catarina Zapoquila",
    "Santa Cruz Acatepec",
    "Santa Cruz Amilpas",
    "Santa Cruz de Bravo",
    "Santa Cruz Itundujia",
    "Santa Cruz Mixtepec",
    "Santa Cruz Nundaco",
    "Santa Cruz Papalutla",
    "Santa Cruz Tacache de Mina",
    "Santa Cruz Tacahua",
    "Santa Cruz Tayata",
    "Santa Cruz Xitla",
    "Santa Cruz Xoxocotlán",
    "Santa Cruz Zenzontepec",
    "Santa Gertrudis",
    "Santa Inés del Monte",
    "Santa Inés Yatzeche",
    "Santa Lucía del Camino",
    "Santa Lucía Miahuatlán",
    "Santa Lucía Monteverde",
    "Santa Lucía Ocotlán",
    "Santa María Alotepec",
    "Santa María Apazco",
    "Santa María la Asunción",
    "Heroica Ciudad de Tlaxiaco",
    "Ayoquezco de Aldama",
    "Santa María Atzompa",
    "Santa María Camotlán",
    "Santa María Colotepec",
    "Santa María Cortijo",
    "Santa María Coyotepec",
    "Santa María Chachoápam",
    "Villa de Chilapa de Díaz",
    "Santa María Chilchotla",
    "Santa María Chimalapa",
    "Santa María del Rosario",
    "Santa María del Tule",
    "Santa María Ecatepec",
    "Santa María Guelacé",
    "Santa María Guienagati",
    "Santa María Huatulco",
    "Santa María Huazolotitlán",
    "Santa María Ipalapa",
    "Santa María Ixcatlán",
    "Santa María Jacatepec",
    "Santa María Jalapa del Marqués",
    "Santa María Jaltianguis",
    "Santa María Lachixío",
    "Santa María Mixtequilla",
    "Santa María Nativitas",
    "Santa María Nduayaco",
    "Santa María Ozolotepec",
    "Santa María Pápalo",
    "Santa María Peñoles",
    "Santa María Petapa",
    "Santa María Quiegolani",
    "Santa María Sola",
    "Santa María Tataltepec",
    "Santa María Tecomavaca",
    "Santa María Temaxcalapa",
    "Santa María Temaxcaltepec",
    "Santa María Teopoxco",
    "Santa María Tepantlali",
    "Santa María Texcatitlán",
    "Santa María Tlahuitoltepec",
    "Santa María Tlalixtac",
    "Santa María Tonameca",
    "Santa María Totolapilla",
    "Santa María Xadani",
    "Santa María Yalina",
    "Santa María Yavesía",
    "Santa María Yolotepec",
    "Santa María Yosoyúa",
    "Santa María Yucuhiti",
    "Santa María Zacatepec",
    "Santa María Zaniza",
    "Santa María Zoquitlán",
    "Santiago Amoltepec",
    "Santiago Apoala",
    "Santiago Apóstol",
    "Santiago Astata",
    "Santiago Atitlán",
    "Santiago Ayuquililla",
    "Santiago Cacaloxtepec",
    "Santiago Camotlán",
    "Santiago Comaltepec",
    "Villa de Santiago Chazumba",
    "Santiago Choápam",
    "Santiago del Río",
    "Santiago Huajolotitlán",
    "Santiago Huauclilla",
    "Santiago Ihuitlán Plumas",
    "Santiago Ixcuintepec",
    "Santiago Ixtayutla",
    "Santiago Jamiltepec",
    "Santiago Jocotepec",
    "Santiago Juxtlahuaca",
    "Santiago Lachiguiri",
    "Santiago Lalopa",
    "Santiago Laollaga",
    "Santiago Laxopa",
    "Santiago Llano Grande",
    "Santiago Matatlán",
    "Santiago Miltepec",
    "Santiago Minas",
    "Santiago Nacaltepec",
    "Santiago Nejapilla",
    "Santiago Nundiche",
    "Santiago Nuyoó",
    "Santiago Pinotepa Nacional",
    "Santiago Suchilquitongo",
    "Santiago Tamazola",
    "Santiago Tapextla",
    "Villa Tejúpam de la Unión",
    "Santiago Tenango",
    "Santiago Tepetlapa",
    "Santiago Tetepec",
    "Santiago Texcalcingo",
    "Santiago Textitlán",
    "Santiago Tilantongo",
    "Santiago Tillo",
    "Santiago Tlazoyaltepec",
    "Santiago Xanica",
    "Santiago Xiacuí",
    "Santiago Yaitepec",
    "Santiago Yaveo",
    "Santiago Yolomécatl",
    "Santiago Yosondúa",
    "Santiago Yucuyachi",
    "Santiago Zacatepec",
    "Santiago Zoochila",
    "Nuevo Zoquiápam",
    "Santo Domingo Ingenio",
    "Santo Domingo Albarradas",
    "Santo Domingo Armenta",
    "Santo Domingo Chihuitán",
    "Santo Domingo de Morelos",
    "Santo Domingo Ixcatlán",
    "Santo Domingo Nuxaá",
    "Santo Domingo Ozolotepec",
    "Santo Domingo Petapa",
    "Santo Domingo Roayaga",
    "Santo Domingo Tehuantepec",
    "Santo Domingo Teojomulco",
    "Santo Domingo Tepuxtepec",
    "Santo Domingo Tlatayápam",
    "Santo Domingo Tomaltepec",
    "Santo Domingo Tonalá",
    "Santo Domingo Tonaltepec",
    "Santo Domingo Xagacía",
    "Santo Domingo Yanhuitlán",
    "Santo Domingo Yodohino",
    "Santo Domingo Zanatepec",
    "Santos Reyes Nopala",
    "Santos Reyes Pápalo",
    "Santos Reyes Tepejillo",
    "Santos Reyes Yucuná",
    "Santo Tomás Jalieza",
    "Santo Tomás Mazaltepec",
    "Santo Tomás Ocotepec",
    "Santo Tomás Tamazulapan",
    "San Vicente Coatlán",
    "San Vicente Lachixío",
    "San Vicente Nuñú",
    "Silacayoápam",
    "Sitio de Xitlapehua",
    "Soledad Etla",
    "Villa de Tamazulápam del Progreso",
    "Tanetze de Zaragoza",
    "Taniche",
    "Tataltepec de Valdés",
    "Teococuilco de Marcos Pérez",
    "Teotitlán de Flores Magón",
    "Teotitlán del Valle",
    "Teotongo",
    "Tepelmeme Villa de Morelos",
    "Heroica Villa Tezoatlán de Segura y Luna, Cuna de la Independencia de Oaxaca",
    "San Jerónimo Tlacochahuaya",
    "Tlacolula de Matamoros",
    "Tlacotepec Plumas",
    "Tlalixtac de Cabrera",
    "Totontepec Villa de Morelos",
    "Trinidad Zaachila",
    "La Trinidad Vista Hermosa",
    "Unión Hidalgo",
    "Valerio Trujano",
    "San Juan Bautista Valle Nacional",
    "Villa Díaz Ordaz",
    "Yaxe",
    "Magdalena Yodocono de Porfirio Díaz",
    "Yogana",
    "Yutanduchi de Guerrero",
    "Villa de Zaachila",
    "San Mateo Yucutindoo",
    "Zapotitlán Lagunas",
    "Zapotitlán Palmas",
    "Santa Inés de Zaragoza",
    "Zimatlán de Álvarez",
  ],
  /*21*/ [""],
  /*22*/ [""],
  /*23*/ [""],
  /*24*/ [""],
  /*25*/ [""],
  /*26*/ [""],
  /*27*/ [""],
  /*28*/ [
    "Abasolo",
    "Aldama",
    "Altamira",
    "Antiguo Morelos",
    "Burgos",
    "Bustamante",
    "Camargo",
    "Casas",
    "Ciudad Madero",
    "Cruillas",
    "Gómez Farías",
    "González",
    "Güémez",
    "Guerrero",
    "Gustavo Díaz Ordaz",
    "Hidalgo",
    "Jaumave",
    "Jiménez",
    "Llera",
    "Mainero",
    "El Mante",
    "Matamoros",
    "Méndez",
    "Mier",
    "Miguel Alemán",
    "Miquihuana",
    "Nuevo Laredo",
    "Nuevo Morelos",
    "Ocampo",
    "Padilla",
    "Palmillas",
    "Reynosa",
    "Río Bravo",
    "San Carlos",
    "San Fernando",
    "San Nicolás",
    "Soto la Marina",
    "Tampico",
    "Tula",
    "Valle Hermoso",
    "Victoria",
    "Villagrán",
    "Xicoténcatl",
  ],
  /*29*/ [""],
  /*30*/ [
    "Acajete",
    "Acatlán",
    "Acayucan",
    "Actopan",
    "Acula",
    "Acultzingo",
    "Camarón de Tejeda",
    "Alpatláhuac",
    "Alto Lucero de Gutiérrez Barrios",
    "Altotonga",
    "Alvarado",
    "Amatitlán",
    "Naranjos Amatlán",
    "Amatlán de los Reyes",
    "Angel R. Cabada",
    "La Antigua",
    "Apazapan",
    "Aquila",
    "Astacinga",
    "Atlahuilco",
    "Atoyac",
    "Atzacan",
    "Atzalan",
    "Tlaltetela",
    "Ayahualulco",
    "Banderilla",
    "Benito Juárez",
    "Boca del Río",
    "Calcahualco",
    "Camerino Z. Mendoza",
    "Carrillo Puerto",
    "Catemaco",
    "Cazones de Herrera",
    "Cerro Azul",
    "Citlaltépetl",
    "Coacoatzintla",
    "Coahuitlán",
    "Coatepec",
    "Coatzacoalcos",
    "Coatzintla",
    "Coetzala",
    "Colipa",
    "Comapa",
    "Córdoba",
    "Cosamaloapan de Carpio",
    "Cosautlán de Carvajal",
    "Coscomatepec",
    "Cosoleacaque",
    "Cotaxtla",
    "Coxquihui",
    "Coyutla",
    "Cuichapa",
    "Cuitláhuac",
    "Chacaltianguis",
    "Chalma",
    "Chiconamel",
    "Chiconquiaco",
    "Chicontepec",
    "Chinameca",
    "Chinampa de Gorostiza",
    "Las Choapas",
    "Chocamán",
    "Chontla",
    "Chumatlán",
    "Emiliano Zapata",
    "Espinal",
    "Filomeno Mata",
    "Fortín",
    "Gutiérrez Zamora",
    "Hidalgotitlán",
    "Huatusco",
    "Huayacocotla",
    "Hueyapan de Ocampo",
    "Huiloapan de Cuauhtémoc",
    "Ignacio de la Llave",
    "Ilamatlán",
    "Isla",
    "Ixcatepec",
    "Ixhuacán de los Reyes",
    "Ixhuatlán del Café",
    "Ixhuatlancillo",
    "Ixhuatlán del Sureste",
    "Ixhuatlán de Madero",
    "Ixmatlahuacan",
    "Ixtaczoquitlán",
    "Jalacingo",
    "Xalapa",
    "Jalcomulco",
    "Jáltipan",
    "Jamapa",
    "Jesús Carranza",
    "Xico",
    "Jilotepec",
    "Juan Rodríguez Clara",
    "Juchique de Ferrer",
    "Landero y Coss",
    "Lerdo de Tejada",
    "Magdalena",
    "Maltrata",
    "Manlio Fabio Altamirano",
    "Mariano Escobedo",
    "Martínez de la Torre",
    "Mecatlán",
    "Mecayapan",
    "Medellín de Bravo",
    "Miahuatlán",
    "Las Minas",
    "Minatitlán",
    "Misantla",
    "Mixtla de Altamirano",
    "Moloacán",
    "Naolinco",
    "Naranjal",
    "Nautla",
    "Nogales",
    "Oluta",
    "Omealca",
    "Orizaba",
    "Otatitlán",
    "Oteapan",
    "Ozuluama de Mascareñas",
    "Pajapan",
    "Pánuco",
    "Papantla",
    "Paso del Macho",
    "Paso de Ovejas",
    "La Perla",
    "Perote",
    "Platón Sánchez",
    "Playa Vicente",
    "Poza Rica de Hidalgo",
    "Las Vigas de Ramírez",
    "Pueblo Viejo",
    "Puente Nacional",
    "Rafael Delgado",
    "Rafael Lucio",
    "Los Reyes",
    "Río Blanco",
    "Saltabarranca",
    "San Andrés Tenejapan",
    "San Andrés Tuxtla",
    "San Juan Evangelista",
    "Santiago Tuxtla",
    "Sayula de Alemán",
    "Soconusco",
    "Sochiapa",
    "Soledad Atzompa",
    "Soledad de Doblado",
    "Soteapan",
    "Tamalín",
    "Tamiahua",
    "Tampico Alto",
    "Tancoco",
    "Tantima",
    "Tantoyuca",
    "Tatatila",
    "Castillo de Teayo",
    "Tecolutla",
    "Tehuipango",
    "Álamo Temapache",
    "Tempoal",
    "Tenampa",
    "Tenochtitlán",
    "Teocelo",
    "Tepatlaxco",
    "Tepetlán",
    "Tepetzintla",
    "Tequila",
    "José Azueta",
    "Texcatepec",
    "Texhuacán",
    "Texistepec",
    "Tezonapa",
    "Tierra Blanca",
    "Tihuatlán",
    "Tlacojalpan",
    "Tlacolulan",
    "Tlacotalpan",
    "Tlacotepec de Mejía",
    "Tlachichilco",
    "Tlalixcoyan",
    "Tlalnelhuayocan",
    "Tlapacoyan",
    "Tlaquilpa",
    "Tlilapan",
    "Tomatlán",
    "Tonayán",
    "Totutla",
    "Tuxpan",
    "Tuxtilla",
    "Ursulo Galván",
    "Vega de Alatorre",
    "Veracruz",
    "Villa Aldama",
    "Xoxocotla",
    "Yanga",
    "Yecuatla",
    "Zacualpan",
    "Zaragoza",
    "Zentla",
    "Zongolica",
    "Zontecomatlán de López y Fuentes",
    "Zozocolco de Hidalgo",
    "Agua Dulce",
    "El Higo",
    "Nanchital de Lázaro Cárdenas del Río",
    "Tres Valles",
    "Carlos A. Carrillo",
    "Tatahuicapan de Juárez",
    "Uxpanapa",
    "San Rafael",
  ],
  /*31*/ [""],
  /*32*/ [""],
];
